name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denolib/setup-deno@master
      with:
        deno-version: 1.5.1
    - name: Run linter & formatter
      run: |
        deno lint --unstable
        deno fmt --check
    - name: Check cli.ts
      run: |
        deno cache cli.ts
    - name: Run tests
      run: |
        deno test -A
